### ISSUE TITLE
Stuck in redis part

### ISSUE THREAD

**Issue by caafff** [n3m6/Sessa#1]
Hello, 

If you do not mind, can I ask one thing?
I installed all the dependencies, basic npms, and key file.
However, as you mentioned, I have to put redis details in config.js.
But I do not know what kind of detail should I put it in. 

If you do not mind, could you share your knowledge?
I am pretty sure your detail and my detail gonna same, cause I gonna use Bitmex as well.

I'm going to wait your reply :)
I hope you help this question.

God bless you and thank you for your generosity. 
Hava a great day!

**Comment by n3m6** [comment]
Redis is a database. Download and install it from https://redis.io
